{% set name = "py3dep" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/py3dep-{{ version }}.tar.gz
  sha256: 594f810db99b3dce428a58ae0af8c39b90ce0ebe0f6d5275663ae28118abdbd8

build:
  entry_points:
    - py3dep = py3dep.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - async-retriever <0.19,>=0.18
    - click >=0.7
    - cytoolz
    - geopandas-base >=1
    - pyogrio
    - numpy >=1.21
    - pygeoogc <0.19,>=0.18
    - pygeoutils <0.19,>=0.18
    - rasterio >=1.2
    - rioxarray >=0.11
    - scipy
    - shapely >=2
    - xarray >=2023.01

test:
  imports:
    - py3dep
  commands:
    - pip check
    - py3dep --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hyriver/py3dep
  summary: Access topography data at any resolution via 3DEP web service of USGS.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
