{% set name = "py3dep" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f044ac107fb63287ae22cec7427d1eaef353ef4dbe0c277ac6a91c4238723d0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - pygeoogc
    - pygeoutils
    - scipy
    - dataclasses

test:
  imports:
    - py3dep

about:
  home: https://github.com/cheginit/py3dep
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Access to 3DEP database for getting data such as DEM data within the US.

  description: |
    Py3DEP is a part Hydrodata software stack that handles accessing to the
    National Map's 3D Eelevation Program for getting data such as DEM, slope,
    and aspect.
  doc_url: https://hydrodata.readthedocs.io
  dev_url: https://github.com/cheginit/py3dep

extra:
  recipe-maintainers:
    - cheginit
